services:
  # --- INFRASTRUCTURE ---
  db:
    image: mariadb:10
    container_name: nest-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - microstore-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microstore-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microstore-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # We expose TWO listeners: 
      # 1. INSIDE Docker (listing-service) -> uses kafka:9092
      # 2. OUTSIDE Docker (PC) -> uses localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_BROKER: kafka:9092
    networks:
      - microstore-network

  nginx:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - listing-service
      - transaction-service
    networks:
      - microstore-network

  # --- MICROSERVICES ---

  auth-service:
    build: ./backend/auth-service
    environment:
      DB_HOST: db
      DB_TYPE: mariadb
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: auth_db
      DB_PORT: 3306
      DB_SYNC: true
      JWT_SECRET_KEY: uAsBw6WxqD
      JWT_EXPIRATION_TIME: "3600"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - microstore-network

  listing-service:
    build: ./backend/listing-service
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: listings_db
      DB_PORT: 3306
      DB_SYNC: true
      JWT_SECRET_KEY: uAsBw6WxqD
      JWT_EXPIRATION_TIME: "3600"
      PORT: 3001
      # Tell the app to look for 'rabbitmq' and 'kafka' services
      RABBITMQ_URL: amqp://rabbitmq:5672
      KAFKA_BROKER: kafka:9092
    ports:
      - "3001:3001"
    depends_on:
      - db
      - rabbitmq
      - kafka
    networks:
      - microstore-network

  transaction-service:
    build: ./backend/transaction-service
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: transaction_db
      DB_PORT: 3306
      DB_SYNC: true
      JWT_SECRET_KEY: uAsBw6WxqD
      JWT_EXPIRATION_TIME: "3600"
      RABBITMQ_URL: amqp://rabbitmq:5672
      PORT: 3002
    ports:
      - "3002:3002"
    depends_on:
      - db
      - rabbitmq
    networks:
      - microstore-network

  analytics-service:
    build: ./backend/analytics-service
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
    networks:
      - microstore-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    networks:
      - microstore-network

volumes:
  mariadbdata:


networks:
  microstore-network:
    driver: bridge
